### ISSUE TITLE
Используй clsx

### ISSUE THREAD

**Issue by didolf** [chichinumber222/MyBlog#2]
https://github.com/chichinumber222/MyBlog/blob/9cf9a538d0345cc9475fead783322f4797cd24c8/src/utils/user-data-with-avatar/user-data-with-avatar.jsx#L7

**Comment by chichinumber222** [comment]
Я уже скачивал classnames и где-то использовал, поэтому не стал что-то другое скачивать. Насколько я понял это примерно то же самое
https://github.com/chichinumber222/MyBlog/blob/847fbb550df1c15f6778adc5b757f1feadb9974a/src/subcomponents/user-data-with-avatar/user-data-with-avatar.jsx#L8

**Comment by chichinumber222** [comment]
Я уже скачивал classnames и где-то использовал, поэтому не стал что-то другое скачивать. Насколько я понял это примерно то же самое
https://github.com/chichinumber222/MyBlog/blob/847fbb550df1c15f6778adc5b757f1feadb9974a/src/subcomponents/user-data-with-avatar/user-data-with-avatar.jsx#L8
