### ISSUE TITLE
Передавай объект вместо функции в mapDispatchToProps

### ISSUE THREAD

**Issue by didolf** [chichinumber222/MyBlog#3]
https://github.com/chichinumber222/MyBlog/blob/9cf9a538d0345cc9475fead783322f4797cd24c8/src/containers/article-page-container/article-page-container.jsx#L11-L14

Почитай про передачу объекта

**Comment by chichinumber222** [comment]
Вот так? Я так везде переделал
https://github.com/chichinumber222/MyBlog/blob/847fbb550df1c15f6778adc5b757f1feadb9974a/src/containers/article-page-container/article-page-container.jsx#L11-L14
