### ISSUE TITLE
Парсить match лучше за пределами useEffect

### ISSUE THREAD

**Issue by didolf** [chichinumber222/MyBlog#4]
https://github.com/chichinumber222/MyBlog/blob/9cf9a538d0345cc9475fead783322f4797cd24c8/src/components/article-page/article-page.jsx#L19-L21

**Comment by chichinumber222** [comment]
https://github.com/chichinumber222/MyBlog/blob/847fbb550df1c15f6778adc5b757f1feadb9974a/src/components/article-page/article-page.jsx#L19-L26

**Comment by chichinumber222** [comment]
https://github.com/chichinumber222/MyBlog/blob/847fbb550df1c15f6778adc5b757f1feadb9974a/src/components/article-page/article-page.jsx#L19-L26
