### ISSUE TITLE
Вынеси MyLink в отдельный компонент на уровне components, utils не подразумевает, что там могут быть компоненты

### ISSUE THREAD

**Issue by didolf** [chichinumber222/MyBlog#6]

**Comment by chichinumber222** [comment]
Я создал папку subcomponents на уровне components. Туда решил складывать небольшие часто используемые компоненты. StyledLink (бывший MyLink) положил туда же.

**Comment by chichinumber222** [comment]
https://github.com/chichinumber222/MyBlog/blob/847fbb550df1c15f6778adc5b757f1feadb9974a/src/subcomponents/styled-link/styled-link.jsx#L1
