### ISSUE TITLE
Лучше вынести компоненты из файла(1 файл - 1 компонент)

### ISSUE THREAD

**Issue by didolf** [chichinumber222/MyBlog#7]
https://github.com/chichinumber222/MyBlog/blob/9cf9a538d0345cc9475fead783322f4797cd24c8/src/components/header/header.jsx#L1

МОжешь вынести в ту же папку, но с `_` в названии файла

**Comment by chichinumber222** [comment]
Ну я сделал по классике так сказать, отдельные папки (group-buttons-non-auth, group-buttons-auth) для этих компонентов. Внутри папки header. Просто у них стили есть...

**Comment by chichinumber222** [comment]
https://github.com/chichinumber222/MyBlog/blob/847fbb550df1c15f6778adc5b757f1feadb9974a/src/components/header/group-buttons-auth/group-buttons-auth.jsx#L1

**Comment by chichinumber222** [comment]
https://github.com/chichinumber222/MyBlog/blob/847fbb550df1c15f6778adc5b757f1feadb9974a/src/components/header/group-buttons-non-auth/group-buttons-non-auth.jsx#L1
